#!/usr/bin/env python3
# patch_frame.py
# Patches custom GPZP tiles into firmware bin, ready to reflash with XGPro
#
# Usage:
#   python3 patch_frame.py <firmware.bin> <frame_name> <strip_dir>
#
# Example:
#   python3 patch_frame.py py25d16hb@sop8.bin skateboard ./my_strips/
#
# strip_dir must contain: strip0.bin strip1.bin strip2.bin strip3.bin
# Generated by encode_frame.py
#
# frame_name options:
#   film, skateboard, neon_star, flower, smiley, graffiti

import sys, os, shutil, zlib, struct

# Resource table: frame -> [CP tile names in order strip0-3]
FRAMES = {
    'film':       ['CP0001', 'CP0002', 'CP0003', 'CP0100'],
    'skateboard': ['CP0101', 'CP0102', 'CP0103', 'CP0200'],
    'neon_star':  ['CP0201', 'CP0202', 'CP0203', 'CP0300'],
    'flower':     ['CP0301', 'CP0302', 'CP0303', 'CP0400'],
    'smiley':     ['CP0401', 'CP0402', 'CP0403', 'CP0500'],
    'graffiti':   ['CP0501', 'CP0502', 'CP0503', None],  # 4th tile at hardcoded offset
}

# Base address of resource data region
BASE = 0x07EC00

# Resource index table offset in firmware
RES_TABLE_OFF = 0x83400
RES_ENTRY_SIZE = 24

def find_offset(fw, name):
    """Look up a CP tile's flash offset from the resource index table."""
    target = name.encode('ascii') + b'GPZP'
    off = RES_TABLE_OFF
    while off < RES_TABLE_OFF + 0x800:
        entry_name = fw[off:off+16].rstrip(b'\x00')
        if entry_name == target:
            idx = struct.unpack_from('<I', fw, off+20)[0]
            flash_off = BASE + idx * 512
            return flash_off
        off += RES_ENTRY_SIZE
    return None

def get_compressed_size(fw, offset):
    """Find the size of the compressed GPZP block by decompressing it."""
    # Decompress to find where it ends — we need to know how many bytes to replace
    chunk = fw[offset+4:offset+200000]
    d = zlib.decompressobj(wbits=-15)
    d.decompress(chunk)
    # unused_data tells us where deflate stream ended
    unused = len(d.unused_data)
    return len(chunk) - unused + 4  # +4 for header

def patch(fw_path, frame_name, strip_dir):
    if frame_name not in FRAMES:
        print(f"Unknown frame '{frame_name}'. Options: {', '.join(FRAMES.keys())}")
        sys.exit(1)

    # Backup first
    backup = fw_path + '.bak'
    if not os.path.exists(backup):
        shutil.copy2(fw_path, backup)
        print(f'Backup -> {backup}')
    else:
        print(f'Backup already exists: {backup}')

    fw = bytearray(open(fw_path, 'rb').read())
    tiles = FRAMES[frame_name]

    for i, tile in enumerate(tiles):
        strip_path = os.path.join(strip_dir, f'strip{i}.bin')
        if not os.path.exists(strip_path):
            print(f'MISSING {strip_path} — skipping')
            continue

        new_data = open(strip_path, 'rb').read()

        # Get flash offset
        if tile is None:
            # graffiti 4th tile hardcoded
            off = 0x0DFA00
        else:
            off = find_offset(fw, tile)
            if off is None:
                print(f'Could not find {tile} in resource table — skipping')
                continue

        # Measure existing block size
        old_size = get_compressed_size(fw, off)
        new_size = len(new_data)

        print(f'  {tile or "0x0DFA00"} @ 0x{off:06X}: old={old_size} new={new_size} bytes', end='')

        if new_size > old_size:
            # New tile is larger — check if it fits in the gap to next block
            # Warn but still write; XGPro flashes the whole bin so gaps are fine
            # as long as we don't overwrite the next resource
            print(f'  WARNING: new tile is {new_size - old_size} bytes larger than original')
        else:
            # Pad remainder with 0xFF (erased flash state)
            padding = bytes([0xFF] * (old_size - new_size))
            new_data = new_data + padding
            print(f'  (+{old_size - new_size} bytes padding)')

        fw[off:off+len(new_data)] = new_data

    # Write patched firmware
    out_path = fw_path.replace('.bin', '_patched.bin')
    open(out_path, 'wb').write(fw)
    print(f'\nPatched firmware -> {out_path}')
    print('Flash with XGPro: open _patched.bin, select PY25D16 SOP8, Program')

if __name__ == '__main__':
    if len(sys.argv) < 4:
        print('Usage: python3 patch_frame.py <firmware.bin> <frame_name> <strip_dir>')
        print('Example: python3 patch_frame.py py25d16hb@sop8.bin skateboard ./my_strips/')
        sys.exit(1)
    patch(sys.argv[1], sys.argv[2], sys.argv[3])
